#!/bin/bash

set -e
set -o pipefail

REPO='SimpleTuner'
OWNER='bghira'
REMOTE='origin'
BRANCH='release'
IMAGE='simpletuner'
DOCKERFILE='Dockerfile'

while getopts "d:C:u:t:f:i:c:r:b:F:" opt; do
	case $opt in
	C) COPY+=( "$OPTARG" ) ;;
	r) REPO="$OPTARG" ;;
	u) OWNER="$OPTARG" ;;
	b) BRANCH="$OPTARG" ;;
	c) COMMIT="$OPTARG" ;;
	i) IMAGE="$OPTARG" ;;
	f) DOCKERFILE="$OPTARG" ;;
	t) TAG="$OPTARG" ;;
	F) FROM="$OPTARG" ;;
	d) DIR="$OPTARG" ;;
	?) exit -1 ;;
	esac
done; shift $((OPTIND - 1))

# e.g. origin/local, upstream/release
if [[ $BRANCH =~ / ]]; then
	REMOTE="${BRANCH/\/*}"
	BRANCH="${BRANCH/*\/}"
fi

if [[ -z "$COMMIT" ]]; then
	COMMIT="$(git log -1 --format=%h $REMOTE/$BRANCH)"
fi

COPY_DIR="$(basename "$(mktemp -d -p .)")"
if [[ "$COPY_DIR" == "." || $COPY_DIR == "./" || $COPY_DIR == "/" ]]; then
	echo "Unsafe COPY_DIR: $COPY_DIR" 1>&2
	exit -1
fi
trap "rm -rf '$COPY_DIR'" ERR EXIT

for i in "${COPY[@]}"; do
	src="${i/:*}"; dst="${i/*:}"
	mkdir -p "$COPY_DIR/$dst"

	# split source arguments on commas so common files
	# only need a single directive
	(
	IFS=$'\n' src=( $(echo "$src" | xargs -rn1 -d ',') )
	for j in "${src[@]}"; do
		cp -Rp -t "$COPY_DIR/$dst" "$j"
	done
	)
done

if [[ -n "$FROM" ]]; then
	TMP="$(mktemp)"; trap "rm -f '$TMP'" ERR EXIT
	sed -e "s#^FROM .*\$#FROM $FROM#g" "$DOCKERFILE" > "$TMP" \
		&& DOCKERFILE="$(cygpath -aw "$TMP")"
fi

docker build \
	${REPO:+--build-arg REPO="$REPO"} \
	${OWNER:+--build-arg OWNER="$OWNER"} \
	${BRANCH:+--build-arg BRANCH="$BRANCH"} \
	${COMMIT:+--build-arg COMMIT="$COMMIT"} \
	${COPY_DIR:+--build-arg COPY_DIR="$COPY_DIR"} \
	-t "$IMAGE:${TAG:-$BRANCH}" \
	--file "$DOCKERFILE" \
	"$@" \
	"${DIR:-.}"
