#!/bin/bash

set -e
set -o pipefail

REPO='SimpleTuner'
OWNER='bghira'
REMOTE='origin'
BRANCH='release'
IMAGE='simpletuner'
DOCKERFILE='Dockerfile'

while getopts "u:t:f:i:c:r:b:" opt; do
	case $opt in
	r) REPO="$OPTARG" ;;
	u) OWNER="$OPTARG" ;;
	b) BRANCH="$OPTARG" ;;
	c) COMMIT="$OPTARG" ;;
	i) IMAGE="$OPTARG" ;;
	f) DOCKERFILE="$OPTARG" ;;
	t) TAG="$OPTARG" ;;
	?) exit -1 ;;
	esac
done; shift $((OPTIND - 1))

# e.g. origin/local, upstream/release
if [[ $BRANCH =~ / ]]; then
	REMOTE="${BRANCH/\/*}"
	BRANCH="${BRANCH/*\/}"
fi

if [[ -z "$COMMIT" ]]; then
	COMMIT="$(git log -1 --format=%h $REMOTE/$BRANCH)"
fi

docker build \
	${REPO:+--build-arg REPO="$REPO"} \
	${OWNER:+--build-arg OWNER="$OWNER"} \
	${BRANCH:+--build-arg BRANCH="$BRANCH"} \
	${COMMIT:+--build-arg COMMIT="$COMMIT"} \
	-t "$IMAGE:${TAG:-$BRANCH}" \
	--file $DOCKERFILE \
	"$@" \
	.
